on:
  - pull_request
  - push

name: build

jobs:
  tests:
    name: PHP-${{ matrix.php }}-${{ matrix.os }}

    env:
      key: cache-v1

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os:
          - ubuntu-latest

        php:
          - "7.4"
          - "8.0"

        composer:
          - "dev-main"

    steps:
      - name: Configure git
        run: git config --global core.autocrlf false

      - name: Checkout
        uses: actions/checkout@v4

      - name: Determine composer cache directory
        run: echo "COMPOSER_CACHE_DIR=$(composer config cache-dir)" >> $GITHUB_ENV

      - name: Cache dependencies installed with composer
        uses: actions/cache@v2
        with:
          path: ${{ env.COMPOSER_CACHE_DIR }}
          key: php${{ matrix.php }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: |
            php${{ matrix.php }}-composer-

      - name: Install composer
        run: composer require --dev "composer/composer:${{ matrix.composer }}" --update-with-dependencies

      - name: Run tests with phpunit
        if: matrix.php != '7.4'
        run: |
          vendor/bin/phpunit --verbose --colors=always
          cd tests/scripts && sh run.sh

      - name: Run tests with phpunit
        if: matrix.php == '7.4'
        run: |
          vendor/bin/phpunit --verbose --coverage-clover=clover.xml --colors=always
          cd tests/scripts && sh run.sh

      - name: Upload code coverage scrutinizer
        if: matrix.php == '7.4'
        run: |
          wget https://scrutinizer-ci.com/ocular.phar
          php ocular.phar code-coverage:upload --format=php-clover coverage.clover
