name: build

on:
  - pull_request
  - push

jobs:
  tests:
    name: PHP-${{ matrix.php }}-${{ matrix.os }}

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os:
          - ubuntu-latest

        php:
          - "7.4"
          - "8.0"
          - "8.1"
          - "8.2"

        composer:
          - "dev-main"

    steps:
      - name: Configure git
        run: git config --global core.autocrlf false

      - name: Checkout
        uses: actions/checkout@v4

      - name: Install composer
        run: composer require --dev "composer/composer:${{ matrix.composer }}" --update-with-dependencies

      - name: Run tests with phpunit
        if: matrix.php != '7.4'
        run: |
          vendor/bin/phpunit --verbose --colors=always
          cd tests/scripts && sh run.sh

      - name: Run tests with phpunit
        if: matrix.php == '7.4'
        run: |
          vendor/bin/phpunit --verbose --coverage-clover=clover.xml --colors=always
          cd tests/scripts && sh run.sh
