on:
  - pull_request
  - push

name: composer-110

jobs:
  tests:
    name: PHP-${{ matrix.php }}-${{ matrix.os }}

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os:
          - ubuntu-latest

        php:
          - "7.2"
          - "7.3"
          - "7.4"
          - "8.0"

        composer:
          - "1.10.*"

    steps:
      - name: Configure git
        run: git config --global core.autocrlf false

      - name: Checkout
        uses: actions/checkout@v4

      - name: Install composer
        run: composer require --dev "composer/composer:${{ matrix.composer }}" --update-with-dependencies

      - name: Run tests with phpunit
        run: |
          vendor/bin/phpunit --verbose --colors=always
          cd tests/scripts && sh run.sh
